# Phần 1: Thư viện numpy

## Bài 1.1

1. Tạo một ma trận 3x3 có tên A với các phần tử sau:

2. Chuyển đổi ma trận A thành kiểu số nguyên và lưu vào ma trận B. In ra ma trận B và kiểu dữ liệu của ma trận B.

3. Tạo một vector u với giá trị $[0.5, 1.5, 2.5]$ và kiểu dữ liệu là `float64`. Cộng ma trận B với vector u và lưu kết quả vào ma trận C. In ra ma trận C và kiểu dữ liệu của ma trận C.

4. Tạo một vector v với giá trị $[10, 20, 30]$ và kiểu dữ liệu là `int32`. Cộng ma trận B với vector v và lưu kết quả vào ma trận D. In ra ma trận D và kiểu dữ liệu của ma trận D.

In [40]:
# Nhập thư viện numpy với bí danh np
import numpy as np
# 1. Tạo một mảng numpy có tên A
import numpy as np
A = np.array([
    [5.1, 8.7, 3.3],
    [4.4, 0.9, 9.5],
    [6.2, 7.5, 1.8]
])
A

# 2. Ma trận B
B = A.astype(int)
B, B.dtype

# 3. Ma trận C
u = np.array([0.5, 1.5, 2.5], dtype='float64')
C = B + u
C, C.dtype

# 4. Ma trận D
v = np.array([10, 20, 30], dtype='int32')
D = B + v
D, D.dtype

(array([[15, 28, 33],
        [14, 20, 39],
        [16, 27, 31]]),
 dtype('int64'))

## Bài 1.2

1. Tạo một ma trận 6x6 có tên M, chứa các số từ 0 đến 35.
2. Trích xuất vùng trung tâm 4x4 của ma trận M và lưu vào ma trận P. Vùng này bao gồm các hàng từ 1 đến 4 và cột từ 1 đến 4.
3. Chọn các hàng 0 và 3 của ma trận con P.
4. Gán giá trị -99 cho các cột 1 và 2 của ma trận M.
5. Trích xuất các giá trị trong các cột lẻ (1, 3, 5) của ma trận M đã bị thay đổi, và tìm các giá trị lớn hơn 20 trong các cột này.

In [41]:
import numpy as np
# 1. Tạo ma trận M
M = np.arange(36).reshape(6, 6)
M

# 2. Trích xuất vùng trung tâm 4x4
P = M[1:5, 1:5]
P

# 3. Chọn các hàng 0 và 3 của P
P[[0, 3], :]

# 4. Gán giá trị cho các cột 1 và 2 của M
M[:, [1, 2]] = -99
M

# 5. Trích xuất giá trị theo điều kiện kết hợp
odd_cols = M[:, [1, 3, 5]]
odd_cols[odd_cols > 20]

array([21, 23, 27, 29, 33, 35])

## Bài 1.3

1. Tạo một ma trận `data` kích thước 4x5 với các giá trị nguyên ngẫu nhiên trong khoảng từ 10 đến 100. In ra ma trận `data`.
2. Tính ma trận chuyển vị của `data` và in ra kết quả.
3. Tính giá trị lớn nhất và nhỏ nhất cho từng hàng trong ma trận `data`. In ra kết quả.
4. Tìm chỉ số của cột chứa giá trị lớn nhất trong mỗi hàng của ma trận `data`. In ra kết quả.

In [42]:
import numpy as np
# 1. Tạo ma trận data
data = np.random.randint(10, 101, size=(4, 5))
data

# 2. Chuyển vị
data.T

# 3. Tính max và min cho từng hàng
np.max(data, axis=1), np.min(data, axis=1)

# 4. Tìm chỉ số của giá trị lớn nhất trong mỗi hàng
np.argmax(data, axis=1)

array([0, 3, 3, 1])

## Bài 1.4

1. Tạo một ma trận chi phí có tên `costs` với các phần tử như sau:
   * Dòng 1: Chi phí nguyên vật liệu, nhân công, vận hành cho sản phẩm A.
   * Dòng 2: Chi phí nguyên vật liệu, nhân công, vận hành cho sản phẩm B.
   * Dòng 3: Chi phí nguyên vật liệu, nhân công, vận hành cho sản phẩm C.
2. Tạo một vector `production_volume` chứa số lượng sản phẩm A, B, C được sản xuất lần lượt là 1000, 500, 1500.
3. Tính tổng chi phí cho từng loại chi phí (Nguyên vật liệu, Nhân công, Vận hành).
4. Tính tổng chi phí cho từng sản phẩm (trên một đơn vị sản phẩm).

In [43]:
import numpy as np
# 1. Tạo ma trận chi phí
costs = np.array([
    [10, 5, 2],
    [12, 7, 3],
    [9, 4, 2.5]
])
print("Ma trận chi phí (Sản phẩm x Loại chi phí)")
print(costs)

# 2. Tạo vector số lượng
production_volume = np.array([1000, 500, 1500])

# 3. Tính tổng chi phí cho từng loại
costs.sum(axis=0)

# 4. Tính tổng chi phí cho từng sản phẩm (trên 1 đơn vị)
costs.sum(axis=1)

Ma trận chi phí (Sản phẩm x Loại chi phí)
[[10.   5.   2. ]
 [12.   7.   3. ]
 [ 9.   4.   2.5]]


array([17. , 22. , 15.5])

## Bài 1.5

1. Tạo một mảng `x` từ -3 đến 3 với bước nhảy là 0.5. In ra mảng `x`.
2. Tính giá trị hàm Sigmoid cho từng phần tử trong mảng `x` và in kết quả ra mảng mới. In ra mảng kết quả sau khi làm tròn đến 4 chữ số thập phân.
Hàm sigmoid là $ f(x) =\frac{1}{1+e^{-x}}$ 

In [44]:
import numpy as np
# 1. Tạo mảng x
x = np.arange(-3, 3.5, 0.5)
x

# 2. Tính hàm Sigmoid
sigmoid = 1 / (1 + np.exp(-x))
np.round(sigmoid, 4)

array([0.0474, 0.0759, 0.1192, 0.1824, 0.2689, 0.3775, 0.5   , 0.6225,
       0.7311, 0.8176, 0.8808, 0.9241, 0.9526])

## Bài 1.6

1. Tạo một ma trận 3x3 có tên A và một vector b

2. Tính định thức của ma trận A và kiểm tra xem ma trận A có khả nghịch hay không.

3. Tính ma trận nghịch đảo của A (A^{-1}).

4. Tìm nghiệm của hệ phương trình $A \cdot x = b$ bằng công thức $x = A^{-1} \cdot b$.

5. Kiểm tra lại nghiệm x bằng cách nhân lại với ma trận A và so sánh kết quả với vector b ban đầu.


In [45]:
import numpy as np

# 1. Tạo ma trận 3x3 có tên A
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f"Ma trận A: \n{A}")

b = np.array([10, 20, 30])
print(f"Vector b: {b}")

# 2. Tính định thức của A
det_A = np.linalg.det(A)
det_A

# 3. Tính ma trận nghịch đảo A^{-1}
try:
    inv_A = np.linalg.inv(A)
except np.linalg.LinAlgError:
    inv_A = None
inv_A

# 4. Tìm nghiệm x bằng công thức x = A^{-1}b
if inv_A is not None:
    x_sol = inv_A @ b
else:
    x_sol = None
x_sol

# Sử dụng toán tử @ để nhân ma trận

# 5. Kiểm tra lại kết quả
if x_sol is not None:
    np.allclose(A @ x_sol, b)
else:
    None

Ma trận A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector b: [10 20 30]


# Phần 2: Thư viện Pandas

## Bài 2.1

1. Tạo một Series từ Dictionary với các thành phố và dân số của chúng như sau:
   * "Hanoi": 8.5 triệu
   * "HCMC": 9.3 triệu
   * "Danang": 1.2 triệu
   * "Haiphong": 2.1 triệu

2. Trích xuất dân số của Hà Nội và Đà Nẵng từ Series và in ra.
3. Thực hiện phép toán vector hóa để chuyển đổi dân số các thành phố từ triệu người sang người (nhân với 1 triệu), sau đó in kết quả ra dưới dạng số nguyên.

In [46]:
import pandas as pd
# 1. Tạo Series từ Dictionary
import pandas as pd
population_dict = {"Hanoi": 8.5, "HCMC": 9.3, "Danang": 1.2, "Haiphong": 2.1}
city_pop = pd.Series(population_dict)
print("Dân số các thành phố (triệu người)")
print(city_pop)

# 2. Trích xuất dữ liệu
city_pop[["Hanoi", "Danang"]]

# 3. Thực hiện phép toán vector hóa
(city_pop * 1_000_000).astype(int)

Dân số các thành phố (triệu người)
Hanoi       8.5
HCMC        9.3
Danang      1.2
Haiphong    2.1
dtype: float64


Hanoi       8500000
HCMC        9300000
Danang      1200000
Haiphong    2100000
dtype: int64

## Bài 2.2

1. Tạo một DataFrame có tên `sales_df` với các cột sau:

   * `nhan_vien`: Danh sách tên nhân viên ("An", "Binh", "Chi", "Dung").
   * `khu_vuc`: Danh sách khu vực làm việc của các nhân viên ("Bắc", "Nam", "Trung", "Bắc").
   * `doanh_so`: Danh sách doanh số bán hàng của các nhân viên (120, 250, 180, 90).
2. Thêm cột "thuong" vào DataFrame. Cột "thuong" có giá trị True nếu doanh số lớn hơn 100, ngược lại là False.
3. Thêm cột "tien\_thuong" vào DataFrame. Cột "tien\_thuong" tính toán tiền thưởng cho nhân viên. Nếu cột "thuong" là True, tiền thưởng sẽ bằng 10% doanh số bán hàng, nếu không sẽ là 0.
4. Xóa cột "khu\_vuc" khỏi DataFrame.

In [47]:
import pandas as pd

# 1. Tạo DataFrame
sales_data = {
    "nhan_vien": ["An", "Binh", "Chi", "Dung"],
    "khu_vuc": ["Bắc", "Nam", "Trung", "Bắc"],
    "doanh_so": [120, 250, 180, 90]
}
sales_df = pd.DataFrame(sales_data)
print("DataFrame Bán hàng ban đầu")
print(sales_df)

# 2. Thêm cột "thuong" dựa trên điều kiện
sales_df["thuong"] = sales_df["doanh_so"] > 100
sales_df

# 3. Thêm cột "tien_thuong"
sales_df["tien_thuong"] = np.where(sales_df["thuong"], sales_df["doanh_so"] * 0.1, 0)
sales_df

# 4. Xóa cột "khu_vuc"
sales_df = sales_df.drop("khu_vuc", axis=1)
sales_df

DataFrame Bán hàng ban đầu
  nhan_vien khu_vuc  doanh_so
0        An     Bắc       120
1      Binh     Nam       250
2       Chi   Trung       180
3      Dung     Bắc        90


nhan_vien  doanh_so  thuong  tien_thuong
0        An       120    True         12.0
1      Binh       250    True         25.0
2       Chi       180    True         18.0
3      Dung        90   False          0.0

## Bài 2.3

1. Tạo một DataFrame với dữ liệu từ 0 đến 15, có kích thước 4x4. Đặt tên cho các chỉ mục hàng là "A", "B", "C", "D" và tên các cột là "W", "X", "Y", "Z".
2. Lựa chọn dữ liệu từ hàng "A" và "C", cột "W" và "Y" bằng cách sử dụng `.loc` (theo nhãn).
3. Lựa chọn dữ liệu từ 2 hàng cuối (vị trí 2 và 3) và 2 cột đầu (vị trí 0 và 1) bằng cách sử dụng `.iloc` (theo vị trí số nguyên).
4. Lấy giá trị tại hàng "B", cột "Z".

In [48]:
import pandas as pd
import numpy as np

# 1. Tạo DataFrame
df = pd.DataFrame(
    np.arange(16).reshape(4, 4),
    index=["A", "B", "C", "D"],
    columns=["W", "X", "Y", "Z"]
)
print("DataFrame gốc")
print(df)

# 2. Lựa chọn bằng .loc (theo nhãn)
df.loc[["A", "C"], ["W", "Y"]]

# 3. Lựa chọn bằng .iloc (theo vị trí số nguyên)
df.iloc[2:4, 0:2]

# 4. Lấy một giá trị đơn lẻ
df.loc["B", "Z"]

DataFrame gốc
    W   X   Y   Z
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15


np.int64(7)

## Bài 2.4

1. Tạo một Series có tên `product_stock` với các giá trị `[10, 50, 30]` và chỉ số `[0, 3, 5]`.
2. Sử dụng phương thức `reindex` để tạo ra các chỉ số từ 0 đến 5. In ra Series sau khi reindex.
3. Sử dụng phương thức `reindex` và điền giá trị bị thiếu bằng phương thức `ffill` (forward-fill). In ra Series sau khi reindex và điền giá trị.

In [49]:
import pandas as pd
import numpy as np

product_stock = pd.Series([10, 50, 30], index=[0, 3, 5])
print("Series ban đầu")
print(product_stock)

# 1. Reindex để tạo ra các chỉ số bị thiếu
product_stock_reindexed = product_stock.reindex(range(6))
product_stock_reindexed

# 2. Reindex và điền giá trị bằng 'ffill' (forward-fill)
product_stock_ffill = product_stock.reindex(range(6), method='ffill')
product_stock_ffill

Series ban đầu
0    10
3    50
5    30
dtype: int64


0    10
1    10
2    10
3    50
4    50
5    30
dtype: int64

## Bài 2.5

1. Tạo một DataFrame với thông tin điểm số của các sinh viên (môn Toán, Lý, Hóa) với các sinh viên là Hùng, Lan, Minh, An. In ra bảng điểm ban đầu.
2. Sắp xếp bảng điểm theo điểm môn Toán giảm dần. In ra bảng điểm sau khi sắp xếp.
3. Tính tổng điểm của mỗi sinh viên và thêm cột tổng điểm vào bảng điểm. In ra bảng điểm với cột tổng điểm.
4. Thực hiện thống kê mô tả cho các môn Toán, Lý và Hóa. In ra kết quả thống kê mô tả.

In [50]:
import pandas as pd
import pandas as pd

# 1. Tạo DataFrame
scores_data = {
    "Toan": [7, 5, 9, 8],
    "Ly": [8, 9, 6, 7],
    "Hoa": [6, 8, 9, 5]
}
student_scores = pd.DataFrame(scores_data, index=["Hùng", "Lan", "Minh", "An"])
print("Bảng điểm ban đầu")
print(student_scores)

# 2. Sắp xếp theo điểm Toán giảm dần
student_scores_sorted = student_scores.sort_values(by="Toan", ascending=False)
student_scores_sorted

# 3. Tính tổng điểm mỗi sinh viên
student_scores["Tong"] = student_scores.sum(axis=1)
student_scores

# 4. Thống kê mô tả
student_scores[["Toan", "Ly", "Hoa"]].describe()

Bảng điểm ban đầu
      Toan  Ly  Hoa
Hùng     7   8    6
Lan      5   9    8
Minh     9   6    9
An       8   7    5


Toan        Ly       Hoa
count  4.000000  4.000000  4.000000
mean   7.250000  7.500000  7.000000
std    1.707825  1.290994  1.825742
min    5.000000  6.000000  5.000000
25%    6.500000  6.750000  5.750000
50%    7.500000  7.500000  7.000000
75%    8.250000  8.250000  8.250000
max    9.000000  9.000000  9.000000

## Bài 2.6

1. Đọc file `transactions.csv` vào DataFrame
2. Hiển thị thông tin cơ bản về DataFrame
   * In ra 5 dòng đầu tiên của DataFrame.
   * Hiển thị thông tin và kiểu dữ liệu của DataFrame.
3. Điền giá trị thiếu trong cột "SoLuong"
   * Điền giá trị thiếu bằng 1 cho cột "SoLuong".
   * Sử dụng `inplace=True` để thay đổi trực tiếp trên DataFrame gốc.
4. Tạo cột mới "ThanhTien"
   * Tính giá trị của cột "ThanhTien" bằng cách nhân cột "DonGia" với cột "SoLuong".
5. Lọc các giao dịch thuộc nhóm hàng "Điện tử"
   * Lọc và in ra các giao dịch có nhóm hàng là "Điện tử".


In [51]:
# Link file: https://drive.google.com/file/d/1Nty62dcwCcSbXWLK6vXUzUoU8s2Qy7j9/view?usp=sharing
# pip install gdown
!gdown 1Nty62dcwCcSbXWLK6vXUzUoU8s2Qy7j9

Downloading...
From: https://drive.google.com/uc?id=1Nty62dcwCcSbXWLK6vXUzUoU8s2Qy7j9
To: e:\Python\Homework\transactions.csv

  0%|          | 0.00/318 [00:00<?, ?B/s]
100%|██████████| 318/318 [00:00<?, ?B/s] 


In [52]:
import pandas as pd
import numpy as np

# 1. Đọc file CSV vào DataFrame
# Giả sử file transactions.csv nằm cùng thư mục với code
df = pd.read_csv("transactions.csv")

print("DataFrame sau khi đọc từ file CSV")
print(df)

# 2. Hiển thị thông tin cơ bản
df.head()
df.info()

# 3. Điền giá trị thiếu trong cột "SoLuong"
df["SoLuong"].fillna(1, inplace=True)
df

# 4. Tạo cột mới "ThanhTien"
df["ThanhTien"] = df["DonGia"] * df["SoLuong"]
df

# 5. Lọc các giao dịch thuộc nhóm hàng "Điện tử"
df[df["NhomHang"] == "Điện tử"]

DataFrame sau khi đọc từ file CSV
    MaGD    SanPham    NhomHang  DonGia  SoLuong      NgayGD
0  TX001   Laptop A     Điện tử    25.0      2.0  2025-07-20
1  TX002   Bàn phím    Phụ kiện     1.2      5.0  2025-07-20
2  TX003  T-shirt B  Thời trang     0.5     10.0  2025-07-21
3  TX004   Màn hình     Điện tử     8.0      NaN  2025-07-21
4  TX005      Chuột    Phụ kiện     0.8      8.0  2025-07-22
5  TX006  Quần Jean  Thời trang     1.5      5.0  2025-07-22
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   MaGD      6 non-null      object 
 1   SanPham   6 non-null      object 
 2   NhomHang  6 non-null      object 
 3   DonGia    6 non-null      float64
 4   SoLuong   5 non-null      float64
 5   NgayGD    6 non-null      object 
dtypes: float64(2), object(4)
memory usage: 420.0+ bytes


C:\Users\Thai Quoc Bao\AppData\Local\Temp\ipykernel_8220\3130558330.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["SoLuong"].fillna(1, inplace=True)


MaGD   SanPham NhomHang  DonGia  SoLuong      NgayGD  ThanhTien
0  TX001  Laptop A  Điện tử    25.0      2.0  2025-07-20       50.0
3  TX004  Màn hình  Điện tử     8.0      1.0  2025-07-21        8.0