
 # Bài  3 - Các thư viện quan trọng trong KHDL của Python

 ## 1. Thư viện Numpy

 ## 2. Thư viện Pandas

## 1. Thư viện Numpy


 - Giới thiệu `Numpy`
 - Mảng đa chiều (`ndarray`)
 - Chỉ số trong mảng
 - Biểu thức điều kiện Where
 - Các phép toán trên mảng
 - Các hàm toán học trên mảng
 - Sinh số ngẫu nhiên
 - Các hàm (phương thức) thống kê trên mảng
 - Kết hợp thống kê với boolean
 - Các phép toán giữa các mảng
 - Các phép toán đại số tuyến tính

###  Giới thiệu `Numpy`


* `NumPy` (Numerical Python) là một thư viện để xử lý tính toán số học và dữ liệu dạng mảng (`array`) hiệu quả.

* Đặc điểm nổi bật:

    - Mảng đa chiều (`ndarray`)

    - Tốc độ tính toán cao

    - Tiết kiệm bộ nhớ

    - Hỗ trợ broadcasting: cho phép tính toán giữa các mảng kích thước khác nhau

    - Có các hàm toán học mạnh mẽ

### Mảng đa chiều (ndarray)


 * ndarray (`n-dimensional array`)  dùng để lưu trữ và xử lý dữ liệu dạng mảng nhiều chiều.

 * Mọi phần tử trong ndarray phải cùng một kiểu dữ liệu (`int, float, bool,...`).



 * Hỗ trợ tính toán vector hóa: thực hiện phép toán trên toàn bộ mảng mà không cần vòng lặp.

In [95]:
# Tạo mảng 1 chiều từ list:
import numpy as np

A1 = np.array([1, 2, 3])
print(A1)

[1 2 3]


In [96]:
# Kiểm tra số chiều, kích thước mỗi chiều của mảng A1
print(A1.ndim) 
print(A1.shape) 

1
(3,)


In [97]:
# Tạo mảng 2 chiều từ list: 
import numpy as np

A2 = np.array([[1, 2, 3], [4, 5, 6]])
print(A2)

[[1 2 3]
 [4 5 6]]


In [98]:
# Kiểm tra số chiều, kích thước mỗi chiều của mảng A1
print(A2.ndim) 
print(A2.shape) 

2
(2, 3)


In [99]:
# Tạo mảng 3 chiều từ list
import numpy as np

A3 = np.array([[[1, 2, 3], [3, 4, 6]], [[7, 8, 9],[10,11,12]]])
print(A3)

[[[ 1  2  3]
  [ 3  4  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [100]:
# Kiểm tra số chiều, kích thước mỗi chiều của mảng A1

print(A3.ndim) 

print(A3.shape)

3
(2, 2, 3)


### Tạo mảng số học

In [101]:
# Mảng 1 chiều 
import numpy as np
A= np.arange(10)
A


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
# Mảng 1 chiều 
import numpy as np
A1= np.arange(0,10, 2)
A1

array([0, 2, 4, 6, 8])

In [103]:
# Mảng 2 chiều 
import numpy as np
A2= np.arange(10).reshape(2,5)
A2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
# Mảng 3 chiều 
import numpy as np
A3= np.arange(12).reshape(3,2,2)
A3

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

### Một số mảng đặc biệt


- Mảng chứa  toàn số 1
- Mảng chứa toàn số 0 
- Tạo mảng  có các giá trị giống nhau
- Mảng ma trận đơn vị

In [105]:
# Mảng chứa toàn số 0 
import numpy as np
A0 = np.zeros(8).reshape(2,4)
A0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
# Mảng chứa  toàn số 1
import numpy as np
A1= np.ones(12).reshape(3,4)
A1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [107]:
# Tạo mảng  có các giá trị giống nhau
import numpy as np
full =np.full((3,2),100)
print(full)

[[100 100]
 [100 100]
 [100 100]]


In [108]:
# Mảng ma trận đơn vị
import numpy as np
I = np.eye(4)
I 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Chỉ số trong mảng


- Chỉ số trong mảng 1 chiều
- Chỉ số trong mảng đa chiều
- Chỉ số kiểu logical (Boolean Indexing)

### Chỉ số trong mảng 1 chiều

In [109]:
# Mảng 1 chiều chỉ số giống như list
import numpy as np
A= np.arange(10)
print(A)
A1 =A[:3] 
A1 # Khung nhìn 3 phân tử đầu của A

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2])

In [110]:
# Thay đổi giá trị trên khung nhìn sẽ thay đổi giá trị trên mảng 
A1[0] =10
print(A1)
A

[10  1  2]


array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [111]:
# Lấy giá trị trong khung nhìn bằng cách copy

A2= A[:3].copy()
A2[0] =9
print(A2)
print(A)

[9 1 2]
[10  1  2  3  4  5  6  7  8  9]



### Chỉ số trong mảng đa chiều

In [112]:
import numpy as np
A = np.arange(12).reshape(3,4)
print(A)

# Truy xuất phần tử ở vị trí dòng 2 cột 4

print(A[1,3])   
print(A[1][3])  

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
7
7


In [113]:
import numpy as np
A = np.arange(12).reshape(3,4)
print(A)

# Truy xuất dòng thứ 2 trong mảng
print(A[1,:])  


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]


In [114]:
import numpy as np
A = np.arange(12).reshape(3,4)
print(A)

# Truy xuất cột trong mảng 


print(A[:,1]) 




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 5 9]


In [115]:
import numpy as np
A = np.arange(12).reshape(3,4)
print(A)

# Truy xuất mảng con qua lát cắt  

print(A[1:3, 1:4])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]


In [116]:
import numpy as np
A = np.arange(12).reshape(3,4)
print(A)
# Truy xuất mảng con  qua list chỉ số
print(A[[0,2], [1,3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1 11]


In [117]:
# Mảng 3 chiều 
import numpy as np
A =np.arange(12).reshape(2,2,3)
print(A, '\n')
print(A[0], '\n')
print(A[0,1], '\n')
print(A[0,1,2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] 

[[0 1 2]
 [3 4 5]] 

[3 4 5] 

5


### Chỉ số kiểu logical (Boolean Indexing)

In [118]:
import numpy as np
A= np.arange(6)

print(A)
print(A>3)



[0 1 2 3 4 5]
[False False False False  True  True]


In [119]:
# Tạo mảng 1 chiều gồm các số chẵn <100
import numpy as np
A=np.arange(100)
B= A[A%2==0]
B

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

## Biểu thức điều kiện Where


    np.where(ĐK, x, y)

Nếu điều kiện đúng thì chọn x, sai thì chọn y

In [120]:
# Tạo mảng 1 chiều có các số từ 0 đên 9
# Thay chữ số chẵn bằng "Chẵn", chữ số lẻ bằng "Lẻ"


A =np.arange(10)
B = np.where(A%2==0,'Chẵn', 'Lẻ')
print(A)
print(B)

[0 1 2 3 4 5 6 7 8 9]
['Chẵn' 'Lẻ' 'Chẵn' 'Lẻ' 'Chẵn' 'Lẻ' 'Chẵn' 'Lẻ' 'Chẵn' 'Lẻ']


In [121]:
# Tạo mảng 1 chiều có các số từ 0 đên 9
# Thay chữ số chẵn bằng "Chẵn", các chữ số lẻ giữ nguyên

A =np.arange(10)
B = np.where(A%2==0,'Chẵn', A)
print(A)
print(B)

[0 1 2 3 4 5 6 7 8 9]
['Chẵn' '1' 'Chẵn' '3' 'Chẵn' '5' 'Chẵn' '7' 'Chẵn' '9']


In [122]:
# Tạo ra mảng từ list: [1, 2, 7, -3, -4]
# Tìm các số chẵn đổi thành  100. 


A =np.array([1, 2, 7, -3, -4])

B = np.where(A%2==0,100,A)
print(A)
print(B)

[ 1  2  7 -3 -4]
[  1 100   7  -3 100]


In [123]:
# Tạo ra mảng từ list: [1, 2, 7, -3, -4]
# Tìm các số âm đổi thành 0


A =np.array([1, 2, 7, -3, -4])

B = np.where(A<0,0,A)

print(A)
print(B)

[ 1  2  7 -3 -4]
[1 2 7 0 0]


In [124]:
# # Tạo ra mảng từ list: [1, 2, 7, -3, -4]
# Tìm các số âm đổi thành giá trị trung bình trong mảng


A =np.array([1, 2, 7, -3, -4])

B = np.where(A<0, A.mean(), A)

print(A)
print(B)

[ 1  2  7 -3 -4]
[1.  2.  7.  0.6 0.6]


## Các phép toán trên mảng

 Tạo ra một mảng 2 chiều A size 2x4 gồm các số

 Thực hiện các phép toán: A+10, A-10, A*10, A/10, A**2 
 

In [125]:
import numpy as np  
A = np.arange(8).reshape(2,4)

print(A)
print(A+10)

[[0 1 2 3]
 [4 5 6 7]]
[[10 11 12 13]
 [14 15 16 17]]


In [126]:
import numpy as np  
A = np.arange(8).reshape(2,4)
print(A)
print(A*10)

[[0 1 2 3]
 [4 5 6 7]]
[[ 0 10 20 30]
 [40 50 60 70]]


In [127]:
import numpy as np  
A = np.arange(8).reshape(2,4)
print(A)
print(A/10)

[[0 1 2 3]
 [4 5 6 7]]
[[0.  0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7]]


In [128]:
import numpy as np  
A = np.arange(8).reshape(2,4)
print(A)
print(A**2)


[[0 1 2 3]
 [4 5 6 7]]
[[ 0  1  4  9]
 [16 25 36 49]]


## Các hàm toán học trên mảng




| Hàm | Mô tả |
|---|---|
| `abs(A)` | $ \|A\| $ |
| `sqrt(A) ,A**0.5` | $\sqrt{A}$ |
| `square(A), A**2` | $A^2$ |
| `exp(A)` | $e^A$  |
| `log(A)`, `log10(A)`, `log2(A)` | $ln(A), log_{10}(A), log_2(A)$ |
| `sign(A)` | $1 (A>0), -1 (A<0), 0 (A=0) $|
| `ceil()`, `floor()` | Làm tròn lên, làm tròn xuống |
| `rint()` | Làm tròn đến số nguyên gần nhất (ưu tiên chẵn). |
| `modf()` | Trả về phần phân số và phần nguyên. |
| `isnan()`, `isfinite()`, `isinf()` |Kiểm tra số, hữu hạn, vô cùng lớn |
| `cos()`, `sin()`, `tan()`... | Các hàm lượng giác. |

In [129]:
import numpy as np
A =np.array([-2, 9])
# Lấy trị tuyệt đối các phần tử của A

np.abs(A)

array([2, 9])

In [130]:
import numpy as np
A =np.array([1, 9])
# Lấy căn bậc 2 các phần tử của A 

np.sqrt(A)

array([1., 3.])

In [131]:
import numpy as np
A =np.array([1, 100])
# Lấy logarit cơ số 10 các phần tử của A

np.log10(A)

array([0., 2.])

In [132]:
import numpy as np
A =np.array([-3, 0, 9])

# Lấy dấu các phần tử của A

np.sign(A)

array([-1,  0,  1])

In [133]:
import numpy as np
A =np.array([1.2, -1.6])

# Làm tròn lên các phần tử của A
 
np.ceil(A)

array([ 2., -1.])

In [134]:
import numpy as np
A =np.array([1.2, -1.6])

# Làm tròn xuống các phần tử của A
np.floor(A)

array([ 1., -2.])

In [135]:
import numpy as np
A =np.array([1.2, 2.5, 3.5])

# Làm tròn các phần tử của A 

np.rint(A)

array([1., 2., 4.])

In [136]:
import numpy as np
A =np.array([1.2, -3.6])
# Tách lấy phần thập phân và phần nguyên trong A

np.modf(A)

(array([ 0.2, -0.6]), array([ 1., -3.]))

In [137]:
import numpy as np
A =np.array([1.2, -1.6])
# Khai căn phần tử của A
# Kiểm tra trong A có phần tử không là số sau khai căn

print(np.sqrt(A))
print(np.isnan(np.sqrt(A)))

[1.09544512        nan]
[False  True]


C:\Users\Thai Quoc Bao\AppData\Local\Temp\ipykernel_13388\2343196243.py:6: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(A))
C:\Users\Thai Quoc Bao\AppData\Local\Temp\ipykernel_13388\2343196243.py:7: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(A)))


## Sinh số ngẫu nhiên


| Hàm | Mô tả |
|---|---|
| `integers(a, b, size)` | Sinh số nguyên ngẫu nhiên trong $[a;b)$  |
| `random(size)` | Sinh số thực ngẫu nhiên  trong $ [0;1)$ |
| `uniform(a, b, size)` | Sinh số thực ngẫu nhiên  trong $[a;b)$|
| `standard_normal(size)` | Sinh ngẫu nhiên từ phân phối Chuẩn hoá |
| `normal(mean, var, size)` | Sinh ngẫu nhiên phân phối Chuẩn. |



In [138]:
# Tạo hạt giống seed , rng = Random Number Generator
rng= np.random.default_rng(seed = 123)


In [139]:
rng= np.random.default_rng(seed = 123)
# Sinh số nguyên ngẫu nhiên: integers(start, stop, size)
# Tạo mảng size 2x4 gồm các số tự nhiên <100

N = rng.integers(0,100, size=(2,4))
print( 'sinh số nguyên ngẫu nhiên\n', N)


sinh số nguyên ngẫu nhiên
 [[ 1 68 59  5]
 [90 22 25 18]]


In [140]:
rng= np.random.default_rng(seed = 123)
# Sinh ngẫu nhiên số thực trong [0;1): random(size)
# Tạo mảng sizw 3x5 gồm các số thực ngẫu nhiên thuộc [0;1)

R =rng.random((3,5))

print('Sinh số thực ngẫu nhiên\n' , R)


Sinh số thực ngẫu nhiên
 [[0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]
 [0.81209451 0.923345   0.2765744  0.81975456 0.88989269]
 [0.51297046 0.2449646  0.8242416  0.21376296 0.74146705]]


In [141]:
rng= np.random.default_rng(seed = 123)
# Sinh số thực ngầu nhiên trong [a;b): uniform(a, b, size)
# Tạo mảng sizw 2x3 gồm các số thực lấy ngẫu nhiên trong [-2;10)
U =rng.uniform(-2,10, size = (2, 3))

print('Sinh số thực ngẫu nhiên\n' , U)


Sinh số thực ngẫu nhiên
 [[ 6.18822236 -1.35414777  0.64431847]
 [ 0.21246173  0.11087081  7.74513408]]


In [142]:
rng= np.random.default_rng(seed = 123)
# Sinh số ngẫu nhiên phân phối Chuẩn hoá: standard_normal(size)
# Tạo mảng size 3x4 gồm từ phân phối Chuẩn hoá
N =rng.standard_normal((3,4))
print('Sinh số ngẫu nhiên phân phối Chuẩn hoá\n', N )


Sinh số ngẫu nhiên phân phối Chuẩn hoá
 [[-0.98912135 -0.36778665  1.28792526  0.19397442]
 [ 0.9202309   0.57710379 -0.63646365  0.54195222]
 [-0.31659545 -0.32238912  0.09716732 -1.52593041]]


In [143]:
rng= np.random.default_rng(seed = 123)
# Sinh số ngẫu nhiên có phân phối Chuẩn: normal(mean, var, size)
# Tạo mảng size 2x5 từ phân phối Chuẩn mean =10, Var = 4
N= rng.normal(10, 4, size=(2,5))
print('Sinh số ngẫu nhiên phân phối Chuẩn\n', N)

Sinh số ngẫu nhiên phân phối Chuẩn
 [[ 6.0435146   8.52885339 15.15170105 10.77589768 13.6809236 ]
 [12.30841517  7.45414541 12.16780888  8.7336182   8.71044354]]


## Các hàm, phương thức thống kê trên mảng

### Các hàm thống kê trên mảng

| Hàm | Mô tả |
|---|---|
| `sum(A)` | Tổng các phần tử của A |
| `mean(A)` | Trung bình các phần tử của A |
| `var(A)`,`std(A)`  |Phương sai, độ lệch chuẩn mẫu A |
| `min(A)`, `max(A)` | Giá trị min, max trong A |
| `argmin(A)`, `argmax(A)` | Vị trí đạt min, max trong A |
| `cumsum(A)` | Tổng tích lũy các phần tử trong A |
| `cumprod(A)` | Tích tích lũy các phần tử trong A |

In [144]:
# Sử dụng hàm thống kê:
# Tính các thống kê: Tổng, trung bình, phương sai, độ lệch chuẩn  tổng tích luỹ, tích tích luỹ của A

import numpy as np
A = np.array([10,3,7,6])

print('Tổng:', np.sum(A))
print('Trung bình:', np.mean(A))
print('Phương sai:', np.var(A))
print('Độ lệch chuẩn:', np.std(A))
print('Tổng tích luỹ:', np.cumsum(A))
print('Tích tích luỹ', np.cumprod(A))


Tổng: 26
Trung bình: 6.5
Phương sai: 6.25
Độ lệch chuẩn: 2.5
Tổng tích luỹ: [10 13 20 26]
Tích tích luỹ [  10   30  210 1260]


In [145]:
#Sử dụng phương thức thống kê
# Tính các thống kê: Tổng, trung bình, phương sai, độ lệch chuẩn  tổng tích luỹ, tích tích luỹ của A

import numpy as np
A = np.array([10,3,7,6])

print('Tổng:',  A.sum())
print('Trung bình:',  A.mean())
print('Phương sai:',  A.var())
print('Độ lệch chuẩn:',  A.std())
print('Tổng tích luỹ:',   A.cumsum())
print('Tích tích luỹ',  A.cumprod())


Tổng: 26
Trung bình: 6.5
Phương sai: 6.25
Độ lệch chuẩn: 2.5
Tổng tích luỹ: [10 13 20 26]
Tích tích luỹ [  10   30  210 1260]


## Tính thống kê theo cột, hàng của mảng 2 chiều



 - axis = 0: Tính theo cột
 - axis = 1: Tính theo hàng


In [146]:
# Tính tổng trên mỗi cột, mỗi hàng 

import numpy as np
A = np.array([[10,3,7,6],[5,15,8,2]])
print(A,'\n')



print('Tổng trên mỗi cột:', A.sum(axis=0))
print('Tổng trên mỗi hàng:', A.sum(axis=1), '\n')



[[10  3  7  6]
 [ 5 15  8  2]] 

Tổng trên mỗi cột: [15 18 15  8]
Tổng trên mỗi hàng: [26 30] 



In [147]:
# Tính tổng trên mỗi cột, mỗi hàng 
import numpy as np
A = np.array([[10,3,7,6],[5,15,8,2]])
print(A,'\n')



print('Tổng trên mỗi cột:', A.sum(axis=0))
print('Tổng trên mỗi hàng:', A.sum(axis=1), '\n')



[[10  3  7  6]
 [ 5 15  8  2]] 

Tổng trên mỗi cột: [15 18 15  8]
Tổng trên mỗi hàng: [26 30] 



In [148]:
# Tính trung bình trên mỗi cột, môi hàng
import numpy as np
A = np.array([[10,3,7,6],[5,15,8,2]])
print(A,'\n')

 

print('Trung bình trên mỗi cột:', np.mean(A, axis=0))
print('Trung bình trên mỗi hàng:', np.mean(A, axis=1))


[[10  3  7  6]
 [ 5 15  8  2]] 

Trung bình trên mỗi cột: [7.5 9.  7.5 4. ]
Trung bình trên mỗi hàng: [6.5 7.5]


In [149]:
# Tính trung bình trên mỗi cột, môi hàng 
import numpy as np
A = np.array([[10,3,7,6],[5,15,8,2]])
print(A,'\n')



print('Trung bình trên mỗi cột:', A.mean(axis=0))
print('Trung bình trên mỗi hàng:', A.mean(axis=1))


[[10  3  7  6]
 [ 5 15  8  2]] 

Trung bình trên mỗi cột: [7.5 9.  7.5 4. ]
Trung bình trên mỗi hàng: [6.5 7.5]


##  Kết hợp thống kê với boolean

In [150]:
# Đếm tổng số  giá trị dương trong mảng
import numpy as np
rng= np.random.default_rng(seed = 123)
N =rng.standard_normal((3,4))
print(N,'\n')


print("Số phần tử dương:", np.sum(N>0))




[[-0.98912135 -0.36778665  1.28792526  0.19397442]
 [ 0.9202309   0.57710379 -0.63646365  0.54195222]
 [-0.31659545 -0.32238912  0.09716732 -1.52593041]] 

Số phần tử dương: 6


In [151]:
# Tính tổng các giá trị dương trong mảng
import numpy as np
rng= np.random.default_rng(seed = 123)
N =rng.standard_normal((3,4))
print(N,'\n')


print("Tổng các giá trị dương trong mảng:", np.sum(N[N>0]))




[[-0.98912135 -0.36778665  1.28792526  0.19397442]
 [ 0.9202309   0.57710379 -0.63646365  0.54195222]
 [-0.31659545 -0.32238912  0.09716732 -1.52593041]] 

Tổng các giá trị dương trong mảng: 3.618353910399721


## Tính toán giữa các mảng cùng size

- Tạo 2 mảng A,B có cùng size

- Tính: A+B, A*B, A/B, A//B, A%B, A**B

In [152]:
import numpy as np
A =np.arange(6).reshape(2,3)
B = np.arange(1,12,2).reshape(2,3)
print(A)
print(B)

print(A+B)

[[0 1 2]
 [3 4 5]]
[[ 1  3  5]
 [ 7  9 11]]
[[ 1  4  7]
 [10 13 16]]


In [153]:
import numpy as np
A =np.arange(6).reshape(2,3)
B = np.arange(1,12,2).reshape(2,3)
print(A)
print(B)

print(A*B)

[[0 1 2]
 [3 4 5]]
[[ 1  3  5]
 [ 7  9 11]]
[[ 0  3 10]
 [21 36 55]]


In [154]:
import numpy as np
A =np.arange(6).reshape(2,3)
B = np.arange(1,12,2).reshape(2,3)
print(A)
print(B)

print(A/B)

[[0 1 2]
 [3 4 5]]
[[ 1  3  5]
 [ 7  9 11]]
[[0.         0.33333333 0.4       ]
 [0.42857143 0.44444444 0.45454545]]


## Tính toán giữa các mảng KHÔNG cùng size

In [155]:
import numpy as np

A= np.arange(8).reshape(2,4) 
B = np.array([10, 10, 10,10])

print(A)
print(B)


print(A+B)

[[0 1 2 3]
 [4 5 6 7]]
[10 10 10 10]
[[10 11 12 13]
 [14 15 16 17]]


## Các phép toán đại số tuyến tính (đọc giáo trình)



In [156]:
# Nhân ma trận
import numpy as np
A = np.arange(6).reshape(3,2)
B= np.arange(4).reshape(2,2)

print(A,'\n')
print(B,'\n')
C=np.dot(A, B)
print(C,'\n')


[[0 1]
 [2 3]
 [4 5]] 

[[0 1]
 [2 3]] 

[[ 2  3]
 [ 6 11]
 [10 19]] 



<span style="font-weight: bold; font-size: 28px; color: green; font-family: Arial, sans-serif;">

Giải hệ phương trình 

$\left\{\begin{array}{l}2 x+3 y-4 z=-4 \\7 x+2 y+3 z=20 \\x+4 y+2 z=15\end{array}\right.$

In [157]:
# Giải hệ phương trình với thư viện numpy
A = np.array([[2,3,-4],[7,2,3],[1,4,2]])
B=np.array([-4,20,15]).reshape(3,1)
print(A)
print(B)
A1 =np.linalg.solve(A,B )
print(A1)

[[ 2  3 -4]
 [ 7  2  3]
 [ 1  4  2]]
[[-4]
 [20]
 [15]]
[[1.]
 [2.]
 [3.]]


# 2. Thư viện Pandas
`pandas ="panel data" `: dữ liệu bảng

 `pandas`: Được thiết kế tối ưu cho dữ liệu dạng bảng không đồng nhất

 `numpy`: Dữ liệu đồng nhất (cùng kiểu)

- `Series`:  chuỗi dữ liệu một chiều 
- `DataFrame`:  bảng dữ liệu hai chiều 

`Series` và `DataFrame` thường là lựa chọn hiệu quả và trực quan trong hầu hết các tình huống xử lý dữ liệu thực tế.

## 2.1 Series (chuỗi) 

Mỗi phần tử trong `Series` gồm:
  - Chỉ số (index) 
  - Giá trị dữ liệu (data)
 


### Cú pháp tạo chuỗi: 

`s = pd.Series(list)`

`s = pd.Series(list,index)`


In [158]:
# Tạo chuỗi với chỉ số mặc định

import pandas as pd
l1 =[4, 7, -5, 3]
s1= pd.Series(l1)
print(s1)

0    4
1    7
2   -5
3    3
dtype: int64


In [159]:
import pandas as pd
s2= pd.Series(list('KHDL'))
print(s2)

0    K
1    H
2    D
3    L
dtype: object


### Trích xuất chỉ số và giá trị của `Series`

In [160]:
# Trích xuất chỉ số và mang giá trị trong Series qua thuộc tính: index, array
import pandas as pd
s= pd.Series(['Khoa', 'học', 'dữ', 'liệu'])

print(s)
print("Chỉ số Series:", s.index)
print("Mảng giá trị Series:", s.array)

0    Khoa
1     học
2      dữ
3    liệu
dtype: object
Chỉ số Series: RangeIndex(start=0, stop=4, step=1)
Mảng giá trị Series: <NumpyExtensionArray>
['Khoa', 'học', 'dữ', 'liệu']
Length: 4, dtype: object


In [161]:
# Truy cập các giá trị của chuỗi qua chỉ số
import pandas as pd
s= pd.Series(['Khoa', 'học', 'dữ', 'liệu'])
print(s[0])
print(s[0:2])



Khoa
0    Khoa
1     học
dtype: object


### Gán nhãn cho index

In [162]:
# Tạo nhãn cho chỉ số của chuỗi
import pandas as pd
Tên =['Hạnh','Phúc','Bình','An']
Điểm =[8.2, 6.5, 9.3, 7.8]

sv= pd.Series(Điểm, index= Tên)
print(sv)

Hạnh    8.2
Phúc    6.5
Bình    9.3
An      7.8
dtype: float64


In [163]:
# Truy cập vào giá trị bằng nhãn

print(sv['Phúc'])
print(sv[['Phúc']])
print(sv[['Hạnh','An']])

6.5
Phúc    6.5
dtype: float64
Hạnh    8.2
An      7.8
dtype: float64


In [164]:
# Cập nhật chỉ số cho chuỗi
import pandas as pd
sv= pd.Series([8.2, 6.5, 9.3, 7.8], index= ['Hạnh','Phúc','Bình','An'])
print(sv)
sv.index = ['H','P','B','A']
print(sv)



Hạnh    8.2
Phúc    6.5
Bình    9.3
An      7.8
dtype: float64
H    8.2
P    6.5
B    9.3
A    7.8
dtype: float64


### Tạo chuỗi từ Dict

In [165]:
# Tạo Series từ Dict
import pandas as pd
dic = {'Tôm':250,'Cua':600,'Thịt lợn':150, 'Cá':100}
tp =pd.Series(dic)
print(tp)

Tôm         250
Cua         600
Thịt lợn    150
Cá          100
dtype: int64


### Cập nhật, chỉnh sửa chuỗi

In [166]:
# Thêm giá trị cho chuỗi 
import pandas as pd
sv= pd.Series([8.2, 6.5, 9.3, 7.8], index= ['Hạnh','Phúc','Bình','An'])

print(sv)
sv['Long']=6.8
print(sv)



Hạnh    8.2
Phúc    6.5
Bình    9.3
An      7.8
dtype: float64
Hạnh    8.2
Phúc    6.5
Bình    9.3
An      7.8
Long    6.8
dtype: float64


In [167]:
# Sửa giá trị của chuỗi 
import pandas as pd
sv= pd.Series([8.2, 6.5, 9.3, 7.8], index= ['Hạnh','Phúc','Bình','An'])
print(sv)
sv['Hạnh']=10
print(sv)



Hạnh    8.2
Phúc    6.5
Bình    9.3
An      7.8
dtype: float64
Hạnh    10.0
Phúc     6.5
Bình     9.3
An       7.8
dtype: float64


In [168]:
# Xoá giá trị của chuỗi 
sv= pd.Series([8.2, 6.5, 9.3, 7.8], index= ['Hạnh','Phúc','Bình','An'])
print(sv)
del sv['An']
print(sv)



Hạnh    8.2
Phúc    6.5
Bình    9.3
An      7.8
dtype: float64
Hạnh    8.2
Phúc    6.5
Bình    9.3
dtype: float64


In [169]:
# sắp xếp giá trị trong chuỗi theo chỉ số 

sv= pd.Series([8.2, 6.5, 9.3, 7.8], index= ['Hạnh','Phúc','Bình','An'])
print(sv)
sv1 =pd.Series(sv, index=['Bình','An','Hạnh','Phúc'])
print(sv1)



Hạnh    8.2
Phúc    6.5
Bình    9.3
An      7.8
dtype: float64
Bình    9.3
An      7.8
Hạnh    8.2
Phúc    6.5
dtype: float64


In [170]:
# Series tự căn chỉnh theo chỉ số
sv= pd.Series([8.2, 6.5, 9.3, 7.8], index= ['Hạnh','Phúc','Bình','An'])
sv1 =pd.Series(sv, index=['Bình','An','Hạnh','Phúc'])

print(sv+sv1)

An      15.6
Bình    18.6
Hạnh    16.4
Phúc    13.0
dtype: float64


In [171]:
sv= pd.Series([8.2, 6.5, 9.3, 7.8], index= ['Hạnh','Phúc','Bình','An'])
sv1 =pd.Series(sv, index=['Bình','An','Hạnh','Phúc'])
sv1['Thêm'] =8.2
sv1+sv

An      15.6
Bình    18.6
Hạnh    16.4
Phúc    13.0
Thêm     NaN
dtype: float64

### Các phép toán trên chuỗi (giống trên Numpy)

In [172]:
sv= pd.Series([8.2, 6.5, 9.3, 7.8], index=['Hạnh','Phúc','Bình','An'])  
print(sv*2)
print(sv+2)

Hạnh    16.4
Phúc    13.0
Bình    18.6
An      15.6
dtype: float64
Hạnh    10.2
Phúc     8.5
Bình    11.3
An       9.8
dtype: float64


In [173]:
sv= pd.Series([8.2, 6.5, 9.3, 7.8], index=['Hạnh','Phúc','Bình','An'])
# Tính điểm trung bình của các SV 
print(sv.mean())



7.95


In [174]:
sv= pd.Series([8.2, 6.5, 9.3, 7.8], index=['Hạnh','Phúc','Bình','An'])
# Tính phương sai, độ lệch chuẩn điểm của các sv 
print(sv.var())
print(sv.std())



1.3366666666666671
1.1561430130683086


In [175]:
sv= pd.Series([8.2, 6.5, 9.3, 7.8], index=['Hạnh','Phúc','Bình','An'])
# In ra các SV có điểm >8 và tính điểm TB của các SV đó

print(sv[sv>8])
print((sv[sv>8]).mean())


Hạnh    8.2
Bình    9.3
dtype: float64
8.75


In [176]:
# Tính toán trên Series bằng các hàm của Numpy 
import numpy as np
sv= pd.Series([8.2, 6.5, 9.3, 7.8], index=['Hạnh','Phúc','Bình','An'])  
print(np.mean(sv))


7.95


# 2.2 DataFrame


- `DataFrame` biểu diễn dữ liệu dạng bảng, chứa một tập hợp các cột, mỗi cột có thể là một kiểu giá trị. 

- `DataFrame` có cả chỉ số hàng (`index`) và chỉ số cột (`columns`).

- `DataFrame` như là một từ điển (`Dict`) của các chuỗi (`Series`) có cùng chỉ số.

## Tạo DataFrame:



In [177]:
# 1. Tạo DataFrame từ Dict

import pandas as pd
data ={
    "Sản phẩm":['Tôm','Cua','Cá','Thịt'],
    "Giá bán":[200,300,100,150],
        }
df1 =pd.DataFrame(data)
df1

Sản phẩm  Giá bán
0      Tôm      200
1      Cua      300
2       Cá      100
3     Thịt      150

In [178]:
# 2. Tạo DataFrame từ Dict của  Series

import pandas as pd
SP = pd.Series(['Tôm','Cua','Cá','Thịt'])
Gia =pd.Series([200,300,100,150])


df2 =pd.DataFrame({ "Sản phẩm":SP,"Giá":Gia })
df2

Sản phẩm  Giá
0      Tôm  200
1      Cua  300
2       Cá  100
3     Thịt  150

In [179]:
#3. Tạo DataFrame từ list của lists (hoặc tuple)
import pandas as pd
data =[
    [	'Tôm',	200],
    [	'Cua',	300],
    [	'Cá',	100],
    [	'Thịt',	150]
]

df3 =pd.DataFrame(data, columns=['Sản phẩm','Giá'])
df3


Sản phẩm  Giá
0      Tôm  200
1      Cua  300
2       Cá  100
3     Thịt  150

In [180]:
# 4. Tạo DataFrame từ numpy array

import numpy as np

arr = np.arange(12).reshape(4,3)
df4 = pd.DataFrame(arr, columns=["A", "B", "C"])
df4


A   B   C
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [181]:
# 5. Đọc dữ liệu từ file csv, excel
import pandas as pd
url = 'https://raw.githubusercontent.com/NCT-NEU/Sach_Khoa_hoc_du_lieu_python/refs/heads/main/datasets/iris.xlsx'
df5 = pd.read_excel(url)
df5


Chiều_dài_đài_hoa  Chiều_rộng_đài_hoa  Chiều_dài_cánh_hoa  \
0                  5.1                 3.5                 1.4   
1                  4.9                 3.0                 1.4   
2                  4.7                 3.2                 1.3   
3                  4.6                 3.1                 1.5   
4                  5.0                 3.6                 1.4   
..                 ...                 ...                 ...   
145                6.7                 3.0                 5.2   
146                6.3                 2.5                 5.0   
147                6.5                 3.0                 5.2   
148                6.2                 3.4                 5.4   
149                5.9                 3.0                 5.1   

     Chiều_rộng_cánh_hoa   Loài_hoa  target  
0                    0.2     setosa       0  
1                    0.2     setosa       0  
2                    0.2     setosa       0  
3                    0.2     setosa       0  
4                    0.2     setosa       0  
..                   ...        ...     ...  
145                  2.3  virginica       2  
146                  1.9  virginica       2  
147                  2.0  virginica       2  
148                  2.3  virginica       2  
149                  1.8  virginica       2  

[150 rows x 6 columns]

In [182]:
# Phương thức xem các phần tử đầu  danh sách
df5.head()


Chiều_dài_đài_hoa  Chiều_rộng_đài_hoa  Chiều_dài_cánh_hoa  \
0                5.1                 3.5                 1.4   
1                4.9                 3.0                 1.4   
2                4.7                 3.2                 1.3   
3                4.6                 3.1                 1.5   
4                5.0                 3.6                 1.4   

   Chiều_rộng_cánh_hoa Loài_hoa  target  
0                  0.2   setosa       0  
1                  0.2   setosa       0  
2                  0.2   setosa       0  
3                  0.2   setosa       0  
4                  0.2   setosa       0

In [183]:
# Phương thức xem các phần tử đầu danh sách
df5.head(3)


Chiều_dài_đài_hoa  Chiều_rộng_đài_hoa  Chiều_dài_cánh_hoa  \
0                5.1                 3.5                 1.4   
1                4.9                 3.0                 1.4   
2                4.7                 3.2                 1.3   

   Chiều_rộng_cánh_hoa Loài_hoa  target  
0                  0.2   setosa       0  
1                  0.2   setosa       0  
2                  0.2   setosa       0

In [184]:
# Phương thức xem các phần tử cuối danh sách
df5.tail()

Chiều_dài_đài_hoa  Chiều_rộng_đài_hoa  Chiều_dài_cánh_hoa  \
145                6.7                 3.0                 5.2   
146                6.3                 2.5                 5.0   
147                6.5                 3.0                 5.2   
148                6.2                 3.4                 5.4   
149                5.9                 3.0                 5.1   

     Chiều_rộng_cánh_hoa   Loài_hoa  target  
145                  2.3  virginica       2  
146                  1.9  virginica       2  
147                  2.0  virginica       2  
148                  2.3  virginica       2  
149                  1.8  virginica       2

## Truy xuất vào cột trong DataFrame

In [185]:
import pandas as pd
data ={
    "Sản phẩm":['Tôm','Cua','Cá','Thịt'],
    "Giá":[200,300,100,150],
        }
KH =pd.DataFrame(data)
print(KH)

# Truy xuất cột qua tên như kiểu Dict
KH["Giá"]

  Sản phẩm  Giá
0      Tôm  200
1      Cua  300
2       Cá  100
3     Thịt  150


0    200
1    300
2    100
3    150
Name: Giá, dtype: int64

In [186]:
# Truy xuất cùng lúc nhiều cột

KH[["Giá", "Sản phẩm"]]

Giá Sản phẩm
0  200      Tôm
1  300      Cua
2  100       Cá
3  150     Thịt

In [187]:
# Truy xuất cột qua tên như thuộc tính
KH.Giá

0    200
1    300
2    100
3    150
Name: Giá, dtype: int64

In [188]:
# 1. Thêm cột mới cho df
print(KH)
KH["Lượng bán"] =[20,21,22,30]
KH['Ngày bán'] ="Thứ 2"
KH


  Sản phẩm  Giá
0      Tôm  200
1      Cua  300
2       Cá  100
3     Thịt  150


Sản phẩm  Giá  Lượng bán Ngày bán
0      Tôm  200         20    Thứ 2
1      Cua  300         21    Thứ 2
2       Cá  100         22    Thứ 2
3     Thịt  150         30    Thứ 2

In [189]:
# Xoá cột 
KH1 =KH.copy()
del KH1["Ngày bán"]

KH1


Sản phẩm  Giá  Lượng bán
0      Tôm  200         20
1      Cua  300         21
2       Cá  100         22
3     Thịt  150         30

### Truy xuất vào  hàng trong DataFrame

In [190]:
# Truy xuất vào hàng thông qua chỉ số hàng 
KH.iloc[[0]]

Sản phẩm  Giá  Lượng bán Ngày bán
0      Tôm  200         20    Thứ 2

In [191]:
# Truy xuất vào nhiều hàng thông qua chỉ số hàng 
KH.iloc[[0,3]]

Sản phẩm  Giá  Lượng bán Ngày bán
0      Tôm  200         20    Thứ 2
3     Thịt  150         30    Thứ 2

In [192]:
# Truy xuất các hàng  qua lát cắt chỉ số hàng

KH.iloc[0:2]

Sản phẩm  Giá  Lượng bán Ngày bán
0      Tôm  200         20    Thứ 2
1      Cua  300         21    Thứ 2

In [193]:
# Gán nhãn cho chỉ số hàng
KH.index=["K1","K2","K3","K4"]
KH

Sản phẩm  Giá  Lượng bán Ngày bán
K1      Tôm  200         20    Thứ 2
K2      Cua  300         21    Thứ 2
K3       Cá  100         22    Thứ 2
K4     Thịt  150         30    Thứ 2

In [194]:
# Truy xuất vào hàng qua tên nhãn của hàng

KH.loc[['K1']]

Sản phẩm  Giá  Lượng bán Ngày bán
K1      Tôm  200         20    Thứ 2

In [195]:
KH.loc[['K1','K4']]

Sản phẩm  Giá  Lượng bán Ngày bán
K1      Tôm  200         20    Thứ 2
K4     Thịt  150         30    Thứ 2

In [196]:
#Cập nhật giá trị cho hàng

KH.loc['K1']=["Thịt",150,40, "Thứ 3"]
KH

Sản phẩm  Giá  Lượng bán Ngày bán
K1     Thịt  150         40    Thứ 3
K2      Cua  300         21    Thứ 2
K3       Cá  100         22    Thứ 2
K4     Thịt  150         30    Thứ 2

In [197]:
# Thêm hàng mới
KH.loc['K12']=["Gà",250,3, "Thứ 3"]
KH

Sản phẩm  Giá  Lượng bán Ngày bán
K1      Thịt  150         40    Thứ 3
K2       Cua  300         21    Thứ 2
K3        Cá  100         22    Thứ 2
K4      Thịt  150         30    Thứ 2
K12       Gà  250          3    Thứ 3

In [198]:
# Xoá hàng
KH2 =KH.copy()
KH3 =KH2.drop("K12")
KH3

Sản phẩm  Giá  Lượng bán Ngày bán
K1     Thịt  150         40    Thứ 3
K2      Cua  300         21    Thứ 2
K3       Cá  100         22    Thứ 2
K4     Thịt  150         30    Thứ 2

### Truy xuất vào ô (cell) trong DataFrame

In [199]:
KH

Sản phẩm  Giá  Lượng bán Ngày bán
K1      Thịt  150         40    Thứ 3
K2       Cua  300         21    Thứ 2
K3        Cá  100         22    Thứ 2
K4      Thịt  150         30    Thứ 2
K12       Gà  250          3    Thứ 3

In [200]:
KH.loc["K2","Giá"]

np.int64(300)

In [201]:
KH.iloc[1,2]

np.int64(21)

### Sắp xếp lại thứ tự của hàng, cột: reindex

In [202]:
# Thay đổi thứ tự của hàng

print(KH)

KH1 = KH.reindex(['K2','K3','K1','K5'])
print(KH1)


    Sản phẩm  Giá  Lượng bán Ngày bán
K1      Thịt  150         40    Thứ 3
K2       Cua  300         21    Thứ 2
K3        Cá  100         22    Thứ 2
K4      Thịt  150         30    Thứ 2
K12       Gà  250          3    Thứ 3
   Sản phẩm    Giá  Lượng bán Ngày bán
K2      Cua  300.0       21.0    Thứ 2
K3       Cá  100.0       22.0    Thứ 2
K1     Thịt  150.0       40.0    Thứ 3
K5      NaN    NaN        NaN      NaN


In [203]:
# Thay đổi thứ tự của cột

print(KH)

KH1 = KH.reindex(columns=['Sản phẩm', 'Ngày bán', 'Lượng bán'])
print(KH1)


    Sản phẩm  Giá  Lượng bán Ngày bán
K1      Thịt  150         40    Thứ 3
K2       Cua  300         21    Thứ 2
K3        Cá  100         22    Thứ 2
K4      Thịt  150         30    Thứ 2
K12       Gà  250          3    Thứ 3
    Sản phẩm Ngày bán  Lượng bán
K1      Thịt    Thứ 3         40
K2       Cua    Thứ 2         21
K3        Cá    Thứ 2         22
K4      Thịt    Thứ 2         30
K12       Gà    Thứ 3          3
